# Generated by Django 5.1.15 on 2026-07-13 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInboundEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('team_id', models.CharField(db_index=True, max_length=64)),
                ('channel_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('thread_ts', models.CharField(blank=True, default='', max_length=32)),
                ('event_ts', models.CharField(max_length=32)),
                ('message_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('RESPONDED', 'Responded'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], db_index=True, default='RECEIVED', max_length=16)),
                ('response_ts', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'slack_bot_inbound_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel_id', 'thread_ts'], name='slack_bot_chan_thread')],
            },
        ),
    ]
